// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9zAIcYsgvXb0h7-zLu1l7cdAJOMqv9U4',
    appId: '1:227706015278:web:0fc00f7590444fe37ed9bf',
    messagingSenderId: '227706015278',
    projectId: 'camp-fi-a2be7',
    authDomain: 'camp-fi-a2be7.firebaseapp.com',
    databaseURL:
        'https://camp-fi-a2be7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'camp-fi-a2be7.appspot.com',
    measurementId: 'G-Q7JP4EBMKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8VgK0-TWvthvN1_LKEiNOD4PuxA9EO0Y',
    appId: '1:227706015278:android:be832ba0c11f2f887ed9bf',
    messagingSenderId: '227706015278',
    projectId: 'camp-fi-a2be7',
    databaseURL:
        'https://camp-fi-a2be7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'camp-fi-a2be7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMjvX38j3XhJ6nvQ5q8UWmn7qKOssvGJ4',
    appId: '1:227706015278:ios:fbbd5874c9b329357ed9bf',
    messagingSenderId: '227706015278',
    projectId: 'camp-fi-a2be7',
    databaseURL:
        'https://camp-fi-a2be7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'camp-fi-a2be7.appspot.com',
    iosBundleId: 'com.example.mikrotikApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMjvX38j3XhJ6nvQ5q8UWmn7qKOssvGJ4',
    appId: '1:227706015278:ios:f35211ca0af21b087ed9bf',
    messagingSenderId: '227706015278',
    projectId: 'camp-fi-a2be7',
    databaseURL:
        'https://camp-fi-a2be7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'camp-fi-a2be7.appspot.com',
    iosBundleId: 'com.example.mikrotikApi.RunnerTests',
  );
}
